apiVersion: v1
kind: Secret
metadata:
  name: demo-portal-secret
type: Opaque
stringData:
  DEMO_PORTAL_SECRET_DEV: DEMO_PORTAL_SECRET_DEV_123
  DEMO_PORTAL_SECRET_BASE: DEMO_PORTAL_SECRET_BASE_OVERWRITTEN_IN_DEV