apiVersion: apps/v1
kind: Deployment
metadata:
  name: distroless-webapp-clojure-deployment
  labels:
    app: distroless-webapp-clojure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distroless-webapp-clojure
  template:
    metadata:
      labels:
        app: distroless-webapp-clojure
    spec:
      containers:
        - name: distroless-webapp-clojure
          image: docker.io/dsuprunov/distroless-webapp-clojure:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always


