apiVersion: v1
kind: Service
metadata:
  name:distroless-webapp-clojure-service
spec:
  selector:
    app: distroless-webapp-clojure
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
