apiVersion: v1
kind: Service
metadata:
  name:distroless-webapp-go-service
spec:
  selector:
    app: distroless-webapp-go
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
