apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-portal-deployment
  labels:
    app: demo-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-portal
  template:
    metadata:
      labels:
        app: demo-portal
    spec:
      containers:
        - name: demo-portal
          image: docker.io/dsuprunov/demo-portal:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: demo-portal-base-configmap
            - secretRef:
                name: demo-portal-base-secret
          env:
            - name: DEMO_PORTAL_BASE_ENV_VAR1
              value: base_env_value1
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
