apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-portal-deployment
  labels:
    app: demo-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-portal
  template:
    metadata:
      labels:
        app: demo-portal
    spec:
      containers:
        - name: demo-portal
          image: docker.io/dsuprunov/demo-portal:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DEMO_VAR0
              valueFrom:
                configMapKeyRef:
                  name: demo-portal-configmap
                  key: DEMO_VAR0
            - name: DEMO_SECRET0
              valueFrom:
                secretKeyRef:
                  name: demo-portal-secret
                  key: DEMO_SECRET0
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always

# TODO: docker secret / docker swarn style посмотреть передачу через /var/run/secrets/.env
