apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-portal-deployment
  labels:
    app: demo-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-portal
  template:
    metadata:
      labels:
        app: demo-portal
    spec:
      containers:
        - name: demo-portal
          image: docker.io/dsuprunov/demo-portal:latest
          imagePullPolicy: Always
#          volumeMounts:
#            - { name: config-volume, mountPath: /app/.configmap.env, subPath: .configmap.env }
#            - { name: secret-volume, mountPath: /app/.secret.env, subPath: .secret.env }
#          env:
#            - { name: DEMO_PORTAL_CONFIGMAPGENERATOR_0, valueFrom: { configMapKeyRef: { name: demo-portal-configmap, key: DEMO_PORTAL_CONFIGMAPGENERATOR_0 } } }
#            - { name: DEMO_PORTAL_CONFIGMAPGENERATOR_1, valueFrom: { configMapKeyRef: { name: demo-portal-configmap, key: DEMO_PORTAL_CONFIGMAPGENERATOR_1 } } }
#            - { name: DEMO_PORTAL_CONFIGMAPGENERATOR_2, valueFrom: { configMapKeyRef: { name: demo-portal-configmap, key: DEMO_PORTAL_CONFIGMAPGENERATOR_2 } } }
#            - { name: DEMO_PORTAL_SECRETGENERATOR_0, valueFrom: { secretKeyRef: { name: demo-portal-secret, key: DEMO_PORTAL_SECRETGENERATOR_0 } } }
#            - { name: DEMO_PORTAL_SECRETGENERATOR_1, valueFrom: { secretKeyRef: { name: demo-portal-secret, key: DEMO_PORTAL_SECRETGENERATOR_1 } } }
#            - { name: DEMO_PORTAL_SECRETGENERATOR_2, valueFrom: { secretKeyRef: { name: demo-portal-secret, key: DEMO_PORTAL_SECRETGENERATOR_2 } } }
          envFrom:
            - configMapRef:
              name: demo-portal-configmap
            - secretRef:
              name: demo-portal-secret
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
#      volumes:
#        - { name: config-volume, configMap: { name: demo-portal-configmap, items: [ { key: .configmap.env, path: .configmap.env } ] } }
#        - { name: secret-volume, secret: { secretName: demo-portal-secret, items: [ { key: .secret.env, path: .secret.env } ] } }
      restartPolicy: Always
