resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: demo-portal-configmap
    envs:
      - .configmap.env

secretGenerator:
  - name: demo-portal-secret
    envs:
      - .secret.env