resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: demo-portal-configmap
    literals:
      - DEMO_VAR_GEN0=DEMO_VAR_GEN0
      - DEMO_VAR_GEN1=DEMO_VAR_GEN1
      - DEMO_VAR_GEN2=DEMO_VAR_GEN2

secretGenerator:
  - name: demo-portal-secret
    literals:
      - DEMO_SECRET_GEN0=DEMO_SECRET_GEN0
      - DEMO_SECRET_GEN1=DEMO_SECRET_GEN1
      - DEMO_SECRET_GEN2=DEMO_SECRET_GEN2