name: Deploy Staging

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-staging:
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update ConfigMap
        run: |
          kubectl create configmap demo-portal-configmap \
          --from-literal=DEMO_VAR0=${{ vars.DEMO_VAR0 }} \
          --from-literal=DEMO_VAR1=${{ vars.DEMO_VAR1 }} \
          --from-literal=DEMO_VAR2=${{ vars.DEMO_VAR2 }} \
          -o yaml --dry-run=client | kubectl apply -f -

      - name: Get ConfigMap values
        run: |
          kubectl get configmap demo-portal-configmap -o yaml