name: Deploy Staging

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load environment variables from env-vars.yml
        run: |
          sed 's/: /=/g' infra/demo-portal/overlays/dev/env-vars.yml >> $GITHUB_ENV

      - name: Print env
        run: |
          printenv | grep XGITHUB | sort
