name: Deploy Staging

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    env:
      XGITHUB_ENV_VAR: ${{ vars.XGITHUB_ENV_VAR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print env
        run: |
          env | sort
