name: Deploy Staging

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-staging:
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./infra/demo-portal/overlays/dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create or Update ConfigMap
        run: |
          kubectl create configmap demo-portal-configmap \
            --from-literal=DEMO_VAR0=${{ vars.DEMO_VAR0 }} \
            --from-literal=DEMO_VAR1=${{ vars.DEMO_VAR1 }} \
            --from-literal=DEMO_VAR2=${{ vars.DEMO_VAR2 }} \
            -o yaml --dry-run=client | kubectl apply -f -

      # TODO: добавить версионирование для vars & secrets

      - name: Create or Update Secret
        run: |
          kubectl create secret generic demo-portal-secret \
            --from-literal=DEMO_SECRET0=${{ secrets.DEMO_SECRET0 }} \
            --from-literal=DEMO_SECRET1=${{ secrets.DEMO_SECRET1 }} \
            --from-literal=DEMO_SECRET2=${{ secrets.DEMO_SECRET2 }} \
            -o yaml --dry-run=client | kubectl apply -f -

      - name: Apply Kustomize Configuration
        run: kubectl kustomize | kubectl apply -f -

      - name: Rollout and Restart dependent pods
        run: |
          kubectl rollout restart deployment demo-portal-deployment

      - name: Check Deployment Rollout Status
        run: |
          kubectl rollout status deployment demo-portal-deployment