name: Deploy Staging

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load variables from file
        id: load-vars
        run: |
            echo "variables=$(cat .github/demo-portal-variables.yaml | yq '.variables')" >> $GITHUB_ENV

      - name: Print env
        run: |
          printenv | grep DEMO | sort
