name: Deploy Staging

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load environment variables from env-vars.yml
        run: |
          echo "Loading environment variables for staging"
#          export $(cat infra/demo-portal/overlays/dev/env-vars.yml | sed 's/: +/=/g')
#          set -o allexport
          source infra/demo-portal/overlays/dev/env-vars.yml
          env | grep XGITHUB | sort
#          set +o allexport

      - name: Print env
        run: |
          env | grep XGITHUB | sort
