name: Deploy Staging

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    env:
      DEMO_VAR0: ${{ vars.DEMO_VAR0 }}
      DEMO_VAR1: ${{ vars.DEMO_VAR1 }}
      DEMO_VAR2: ${{ vars.DEMO_VAR2 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print env
        run: |
          printenv | grep DEMO | sort
          echo "---"
          echo "0 - ${{ vars.DEMO_VAR0 }}"
          echo "1 - ${{ vars.DEMO_VAR1 }}"
          echo "2 - ${{ vars.DEMO_VAR2 }}"