name: Deploy Staging

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load variable names from file and create ConfigMap
        run: |
          VARS=$(yq '.variables[]' .github/demo-portal-variables.yaml)
          echo "1 - $VARS"
          echo "2 - ${{ vars.DEMO_VAR0 }}"
          echo "3 - ${{ vars['DEMO_VAR0'] }}"
          for VAR in $VARS; do
            echo "4 - $VAR - ${{ vars[format('{0}', 'DEMO_VAR0')] }}"
          done
          

      - name: Print env
        run: |
          printenv | grep DEMO | sort
