name: Deploy Staging

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-staging:
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./infra/demo-portal/base
    env:
      DEMO_PORTAL_VAR_0: ${{ vars.DEMO_VAR0 }}
      DEMO_PORTAL_VAR_1: ${{ vars.DEMO_VAR0 }}
      DEMO_PORTAL_VAR_2: ${{ vars.DEMO_VAR0 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file(s)
        run: |
          echo "DEMO_PORTAL_CONFIGMAPGENERATOR_0=\"${{ vars.DEMO_VAR0 }}\"" >> .configmap.env
          echo "DEMO_PORTAL_CONFIGMAPGENERATOR_1=\"${{ vars.DEMO_VAR1 }}\"" >> .configmap.env
          echo "DEMO_PORTAL_CONFIGMAPGENERATOR_2=\"${{ vars.DEMO_VAR2 }}\"" >> .configmap.env
          echo "DEMO_PORTAL_SECRETGENERATOR_0=\"${{ secrets.DEMO_SECRET0 }}\"" >> .secret.env
          echo "DEMO_PORTAL_SECRETGENERATOR_0=\"${{ secrets.DEMO_SECRET1 }}\"" >> .secret.env
          echo "DEMO_PORTAL_SECRETGENERATOR_0=\"${{ secrets.DEMO_SECRET2 }}\"" >> .secret.env

      - name: Apply Kustomize Configuration
        run: kubectl kustomize | kubectl apply -f -

      - name: Rollout and Restart dependent pods
        run: |
          kubectl rollout restart deployment demo-portal-deployment

      - name: Check Deployment Rollout Status
        run: |
          kubectl rollout status deployment demo-portal-deployment

      - name: Clean up .env file
        run: rm .configmap.env .secret.env