name: Deploy Staging

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load variable names from file and create ConfigMap
        run: |
          VARS=$(yq '.variables[]' .github/demo-portal-variables.yaml)
          for VAR in $VARS; do
            VALUE=$(eval echo "\$$VAR")
            echo "$VAR $VALUE"
          done

      - name: Print env
        run: |
          printenv | grep DEMO | sort
