name: Deploy Staging

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load variable names from file and create ConfigMap
        id: load-vars
        run: |
          VARS=$(yq '.variables[]' .github/demo-portal-variables.yaml)
          echo $VARS

      - name: Print env
        run: |
          printenv | grep DEMO | sort
